### PR TITLE
Updating models and classes to support polymorphic model mappings

### PR DESCRIPTION
**Pull request by tony98ms**
Hi @namumakwembo, I have created this pull request with the necessary changes to support the custom polymorphic classes . Review please.  #24

### CODE REVIEW

**Comment by namumakwembo** [comment]
Thanks for working on this issue , i'll review it

**Review by namumakwembo — CHANGES_REQUESTED** [review]
Looks good , however some tests are failing , can you please run `vendor/bin/pest --parallel` and `vendor/bin/pint`  to resolve any failing tests

**Comment by tony98ms** [comment]
Of course, give me a moment to review

**Comment by tony98ms** [comment]
I have run the tests and corrected the problem. @namumakwembo

**Review by namumakwembo — APPROVED** [review]
Looks good to me

**Pull request merged**
